### PR TITLE
Compatitability for apktool and instructions for macos

### PR DESCRIPTION
**Pull request by Matr1x-101**

### CODE REVIEW

**Comment by whiteinge** [comment]
Thanks for the updated instructions! You're very right the `-i` flag requires GNU sed on OS X.

What do you think about checking for `gsed` at the top of the existing script and storing which sed to use in a variable instead of making a second copy of the script?

**Comment by Matr1x-101** [comment]
Done!

**Comment by whiteinge** [comment]
Looks great, thanks.

Sorry, one other question I forgot to ask earlier: why the change to hard-code `STOREPASS`? The `/dev/urandom` file should be available on OS X. Is that right or were you seeing other breakage with that command?

**Comment by Matr1x-101** [comment]
Yeah, sorry, it wasn't working. I did that as a temporary fix, since 5 digit passwords weren't working. I'll change that.

**Comment by whiteinge** [comment]
Looks good to me. Thanks for the update!

**Pull request merged**
