### PR TITLE
Make the project compatible with the latest MacOS and Android

### PR DESCRIPTION
**Pull request by soar**
- Make it compatible with the latest MacOS
- Make it compatible with the latest Android

### CODE REVIEW

**Comment by whiteinge** [comment]
Interesting, thanks for the updates. I haven't seen this changes yet. What packages provide `zipalign` and `apksigner`? It's been convenient to get this done with just the JDK, Apktool, and adb so are these new packages strictly required for the same tasks or can we get by without them somehow? If they're required we should add them to the README.

**Comment by soar** [comment]
[zipalign](https://developer.android.com/studio/command-line/zipalign) and [apksigner](https://developer.android.com/studio/command-line/apksigner) are parts of Android SDK. This is the new way to sign APK files, without them a file won't be compatible with the latest Android.

**Comment by whiteinge** [comment]
Dang, Android SDK is a huge dependency. Will you please update the README with that info? Otherwise this looks good to merge.

**Comment by whiteinge** [comment]
Good stuff. Thank you for the updates!

**Pull request merged**
